name: Deploy to DreamHost via SFTP

on:
  push:
    branches:
      - main  # Cambia esto a tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SFTP_USERNAME }}
        server: ${{ secrets.SFTP_HOST }}
        port: 22 # Puerto estándar SFTP
        password: ${{ secrets.SFTP_PASSWORD }}
        local_path: './*'  # Carpeta con tus archivos de producción
        remote_path: '/home/briantux/tuxtlanet.com.mx/'  # Ruta al directorio de tu sitio web
        
        # Configuraciones opcionales
        sftp_only: true
        delete_remote_files: false  # Cuidado con esto, puede borrar archivos existentes
