name: Deploy to SFTP

on:
  push:
    branches:
      - main  # O la rama que estás utilizando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SFTP
      uses: appleboy/sftp-action@v0.1.0
      with:
        host: ${{ secrets.SFTP_HOST }}  # Dirección del servidor SFTP
        username: ${{ secrets.SFTP_USERNAME }}  # Usuario SFTP
        password: ${{ secrets.SFTP_PASSWORD }}  # Contraseña SFTP
        port: 22  # El puerto por defecto para SFTP es el 22
        local-dir: ./  # Ruta a la carpeta de tu repositorio con los archivos a subir
        remote-dir: /home/briantux/tuxtlanet.com.mx/  # Carpeta de destino en el servidor
