name: Deploy to SFTP

on:
  push:
    branches:
      - main  # O la rama que est치s utilizando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SFTP
      uses: appleboy/ssh-action@v0.1.0  # Acci칩n correcta para SFTP
      with:
        host: ${{ secrets.SFTP_HOST }}  # Direcci칩n del servidor SFTP
        username: ${{ secrets.SFTP_USERNAME }}  # Usuario SFTP
        password: ${{ secrets.SFTP_PASSWORD }}  # Contrase침a SFTP
        port: 22  # Puerto para SFTP
        sync: true  # Para sincronizar los archivos
        source: "./"  # Carpeta local de tu repositorio
        target: "/home/briantux/tuxtlanet.com.mx/"  # Carpeta de destino en el servidor
        delete: true  # Eliminar archivos en el servidor que ya no existen localmente (opcional)
